version: '3.3'
services:
  db:
    image: mongo:3
    container_name: mongo_container
    environment:
      - MONGO_INITDB_DATABASE=simian_checker_db
    ports:
      - 27017:27017

  simian-checker-app:
    container_name: simian_app_container
    image: simian-checker
      environment:
        - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db-volume: